version: "3.8"

services:
  postgres:
    image: postgres:17.6
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: imart
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9.8
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: imart
    ports:
      - "5050:80"
    depends_on:
      - postgres

  resin:
    build: ./resin
    container_name: resin
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9042:9042"
      - "9160:9160"
    stdin_open: true
    tty: true
    volumes:
      - ./volumes/resin/webapps:/opt/resin/webapps

